# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: OWF Learn / CSV
pages:
- Home: index.md
- CSV Overview: csv-overview.md
- CSV Syntax: csv-syntax.md
- 'CSV Tools by Language':
  - CSV with Excel: csv-excel.md
  - CSV with Java: csv-java.md
  - CSV with JavaScript: csv-javascript.md
  - CSV with PostgreSQL: csv-postgresql.md
  - CSV with Python: csv-python.md
  - CSV with R: csv-r.md
- Resources: csv-resources.md
theme: readthedocs
repo_url:  https://github.com/OpenWaterFoundation/owf-learn-csv
site_description:  Open Water Foundation Learn CSV
site_author:  Open Water Foundation
site_favicon:  OWF-Logo-Favicon-32x32.png
copyright:  Copyright Open Water Foundation
#extra_css:
#- css/extra.css
# Defaults to all JavaScript in the docs folder
# extra_javascript:
