# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / CSV
nav:
- Home: index.md
- CSV Overview: csv-overview.md
- CSV Syntax: csv-syntax.md
- 'CSV Tools by Technology':
  - CSV with Excel: csv-excel.md
  - CSV with Java: csv-java.md
  - CSV with JavaScript: csv-javascript.md
  - CSV with PostgreSQL: csv-postgresql.md
  - CSV with Python: csv-python.md
  - CSV with R: csv-r.md
  - CSV with TSTool: csv-tstool.md
- Resources: csv-resources.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  'Copyright Open Water Foundation'
# Use extra CSS to customize styles, based on theme
extra_css:
   - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-csv
site_author:  'Open Water Foundation'
site_description: 'Open Water Foundation Learn CSV'
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.png'
